Avoid double evaluation in the MITAMA_TRY macro
LoliGothick/mitama-cpp-result pull request #79
Opened 2020-12-06 21:25 UTC by ken-matsui

When passing a function call like the below,
```cpp
MITAMA_TRY(func(42));
```

this will be expanded that will cause double evaluation:
```cpp
({
    if (func(42).is_err()) {
        using Err = mitama::failure_t<decltype(func(42))::err_type>;
        return std::get<Err>(func(42).into_storage());
    }
    using Ok = mitama::success_t<decltype(func(42))::ok_type>;
    std::get<Ok>(func(42).into_storage()).get();
})
```

So, I fixed the MITAMA_TRY macro to expand like this:
```cpp
({
    const auto result = func(42);
    if (result.is_err()) {
        using Err = mitama::failure_t<decltype(result)::err_type>;
        return std::get<Err>(result.into_storage());
    }
    using Ok = mitama::success_t<decltype(result)::ok_type>;
    std::get<Ok>(result.into_storage()).get();
})
```

2020-12-06 21:53 UTC, LoliGothick reviewed
How about this version?

```cpp
#if defined(__GNUC__) || defined(__clang__)
#define MITAMA_CPP_RESULT_TRY_MAY_NOT_PANIC true
#define MITAMA_TRY( ... )                                                                   \
    ({                                                                                      \
        auto&& result = [&]()->decltype(auto){ return __VA_ARGS__; }();                     \
        if (result.is_err()) {                                                              \
            using Err = mitama::failure_t<std::remove_cvref_t<decltype(result)>::err_type>; \
            return std::get<Err>(result.into_storage());                                    \
            }                                                                               \
        using Ok = mitama::success_t<std::remove_cvref_t<decltype(result)>::ok_type>;       \
        std::get<Ok>(result.into_storage()).get();                                          \
    })
#else
#define MITAMA_CPP_RESULT_TRY_MAY_NOT_PANIC false
#define MITAMA_TRY( result ) result.unwrap()
#define MITAMA_TRY( RESULT ) RESULT.unwrap()
#endif

auto d = MITAMA_TRY(a,b,c); // accepts comma operator (but, who uses it!?)
```

2020-12-06 21:57 UTC, LoliGothick commented
Uh, oh...

```cpp
#if defined(__GNUC__) || defined(__clang__)
#define MITAMA_CPP_RESULT_TRY_MAY_NOT_PANIC true
#define MITAMA_TRY( RESULT ) ... {omitted}
#endif

auto c = MITAMA_TRY(a[a, c]); // error: too many arguments provided to function-like macro invocation
```

2020-12-06 22:11 UTC, LoliGothick requested changes
@ken-matsui 

Uses of the comma operator in subscripting expressions is **deprecated** since C++20 (ref: [P1161R3](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1161r3.html)).

However, lambda introducer has same syntax.

```cpp
auto c = MITAMA_TRY([a, b]{ return a.conj(b); }); // error: too many arguments provided to function-like macro invocation
```

Therefore, the signature needs to be modified.

2020-12-06 23:12 UTC, LoliGothick commented
A `static_assert` might be generating helpful error messages.

```cpp
#define MITAMA_TRY( ... )                                                                   \
    ({                                                                                      \
        static_assert(::mitama::is_result_v<std::remove_cvref_t<decltype(__VA_ARGS__)>>,    \
                      "Even if you accidentally expand an ill-formed expression,"           \
                      "hopefully there will be a human-readable error...");                 \
        auto&& result = [&]()->decltype(auto){ return __VA_ARGS__; }();                     \
...{omitted}
```

2020-12-07 06:15 UTC, ken-matsui commented on test/result_tests.cpp
> +}
The MITAMA_TRY macro now supports comma operator in subscripting expressions of lambda introducer 🎉

2020-12-07 09:04 UTC, LoliGothick approved these changes

2020-12-07 09:04 UTC, merged